//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_Challenge_Project___Pluralsight
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distractor
    {
        public int DistID { get; set; }
        public int QID { get; set; }
        public Nullable<int> Distrctr { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
